import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class GspIssue251ContractTests(unittest.TestCase):
    def test_gpu_neutral_real_time_runner_contract(self) -> None:
        runner = (ROOT / "scripts" / "run_gsp_idle_benchmark.sh").read_text(encoding="utf-8")
        implementation = (ROOT / "scripts" / "run_gsp_idle_benchmark.py").read_text(encoding="utf-8")
        benchmark = (ROOT / "tests" / "performance" / "physics_benchmark.gd").read_text(encoding="utf-8")
        self.assertIn("AEROSIM_GSP_IDLE_WARMUP_SECONDS", runner)
        self.assertIn("AEROSIM_GSP_IDLE_SECONDS", runner)
        self.assertIn("conditioning", implementation)
        self.assertIn("CONDITIONING_SECONDS = 300", implementation)
        self.assertIn("conditioning.environment.raw.json", implementation)
        self.assertIn("D-I-I-D", implementation)
        self.assertIn('RUN_ORDER = ["disabled", "authenticated-idle", "authenticated-idle", "disabled"]', implementation)
        self.assertIn("--remote-debug", implementation)
        self.assertNotIn("--fixed-fps", implementation)
        self.assertIn("time.monotonic()", implementation)
        self.assertIn("telemetry_received", implementation)
        self.assertIn("max_telemetry_gap_seconds", implementation)
        self.assertIn("comparison.json", implementation)
        self.assertIn('"(I_a-D_a)/D_a"', implementation)
        self.assertIn('"(I_b-D_b)/D_b"', implementation)
        self.assertIn('"aggregate_pair_delta_percent"', implementation)
        self.assertIn('abs(aggregate_percent) < 1.0', implementation)
        self.assertIn("package_temperature", implementation)
        self.assertIn("thermal_throttle", implementation)
        self.assertIn("processor_cooling_devices", implementation)
        self.assertIn("cur_state", implementation)
        self.assertIn("max_state", implementation)
        self.assertIn("total_trans", implementation)
        self.assertIn("time_in_state_ms", implementation)
        self.assertIn("processor_cooling_protocol", implementation)
        self.assertIn("feedback_ctrs", implementation)
        self.assertIn("reference_perf", implementation)
        self.assertIn("P(a,b)", implementation)
        self.assertIn("cppc_w1", implementation)
        self.assertIn("cppc_w2", implementation)
        self.assertIn("D_a_D_b", implementation)
        self.assertIn("boundary_snapshots", implementation)
        self.assertIn("configuration_start", implementation)
        self.assertIn("configuration_end", implementation)
        self.assertIn("scaling_driver", implementation)
        self.assertIn("energy_performance_preference", implementation)
        self.assertIn('"status": "UNAVAILABLE"', implementation)
        self.assertIn('"failure_kind"', implementation)
        self.assertIn("measurement_elapsed_monotonic_seconds", implementation)
        self.assertIn("telemetry_frame_times", implementation)
        self.assertIn("PhysicsFrameProfiler", benchmark)
        self.assertIn("EffectWorkload", benchmark)
        self.assertIn("--gsp-mode", benchmark)
        self.assertIn("_run_gsp_phase", benchmark)
        self.assertIn("warmup_elapsed_monotonic_seconds", benchmark)
        self.assertIn("measurement_elapsed_monotonic_seconds", benchmark)
        self.assertNotIn("NVIDIA", implementation)
        self.assertNotIn("--require-adapter", implementation)

    def test_browser_runner_requires_real_correlated_samples(self) -> None:
        runner = (ROOT / "scripts" / "test_gsp_panel_browser.py").read_text(encoding="utf-8")
        self.assertIn("Page.bringToFront", runner)
        self.assertIn("sampleIndex < 100", runner)
        self.assertIn("sampleIndex", runner)
        self.assertIn("clock_sync", runner)
        self.assertNotIn("timeOrigin", runner)

    def test_release_report_is_in_reports_directory(self) -> None:
        self.assertTrue((ROOT / "docs" / "reports" / "task-11-report.md").is_file())
        self.assertFalse((ROOT / "task-11-report.md").exists())
